### ISSUE TITLE
Design doc for cpu offloading feature

### ISSUE THREAD

**Issue by XiaoningDing** [bd-iaas-us/vllm#3]
We already have a brief description about this proposed feature in the vLLM issue (https://github.com/vllm-project/vllm/issues/3563), but we still need a more detailed design document:

* Value proposition and how the feature works
* Feature Design:
    * New vLLM component and changed components, key flows, etc
    * What are the required changes in a model definition
* How it's related to latest hardware (like grace-hopper) and performance/cost comparison

Given this is the priority of the vLLM community for now, we probably need more efforts on value validation and finding actual users.

**Comment by foreverpiano** [comment]
Is there any progress on it? @chenqianfzh. I am going to work on it if not

**Comment by eigen2017** [comment]
@XiaoningDing @chenqianfzh 
感谢！！一直在等待vllm对cpu内存的支持！
这里我有2个疑问：
1。可以满足一部分权重在cpu内存，一部分权重在gpu么？没看到百分数的设置，或者说分配多少cpu内存的设置，还是说是true的话就是默认的自动的？
2.  可以针对所有模型么？我看我们的修改，都深入到了各模型的代码里面，我理解这个应该是比较底层的选项，应该跟各模型的代码没关系吧？

**Comment by eigen2017** [comment]
拜读了https://github.com/vllm-project/vllm/issues/3563
发现是权重在用的时候现加入到显存，不用的时候回到cpu内存。这种方案推理速度会下降多少啊。
这个方案貌似和部分权重一直保持在显存，另一部分权重用的时候加载到显存有点不太一样。

**Comment by foreverpiano** [comment]
@eigen2017 我个人感觉目前版本是比较简单的实现，所以想问问有没有更多的结果 @chenqianfzh 我目前觉得现在是 by layer 的 offload weight，而optimizer, kv_cache并没有offload。

**Comment by eigen2017** [comment]
> @eigen2017 我个人感觉目前版本是比较简单的实现，所以想问问有没有更多的结果 @chenqianfzh 我目前觉得现在是 by layer 的 offload weight，而optimizer, kv_cache并没有offload。

不不，vllm是推理框架，optimizer是不加载的。kv对是推理时才产生的，现在是解决权重在加载阶段显存不够的问题，可能要分开讨论。

**Comment by foreverpiano** [comment]
@eigen2017  对是的，kv cache那边是考虑context的问题，weight是考虑bigmodel的问题

**Comment by foreverpiano** [comment]
我认为是可以做到一部分GPU一部分CPU的，目前实现就是by layer的swap，也就是保持在算的地方在GPU，其余时刻都在CPU

**Comment by eigen2017** [comment]
嗯嗯。可惜不很了解vllm唉

**Comment by eigen2017** [comment]
https://github.com/vllm-project/vllm/issues/3931

**Comment by eigen2017** [comment]
https://github.com/vllm-project/vllm/issues/4369

**Comment by eigen2017** [comment]
到处求人。。

**Comment by chenqianfzh** [comment]
@eigen2017 @foreverpiano 

最近终于有时间专注于cpu offload 了。我对之前的设计做了改动，就是只offload transformer部分的weight。这样一来，GPU需要的memory 依然很低，但是对各个model的改动会比较小，代码好维护。

代码暂时放这里。https://github.com/vllm-project/vllm/compare/main...bd-iaas-us:vllm:qian/new-cpu-offload

我今天改一下文档，回头把相关的链接放这里。

**Comment by chenqianfzh** [comment]
https://docs.google.com/document/d/1qY9SJIRCLn6_p_2jHInW0E8qE2oukgOrH26v62jZy70/edit?usp=sharing

the design doc

**Comment by chenqianfzh** [comment]
the feature is merged in another PR: https://github.com/vllm-project/vllm/pull/6496/files
