### ISSUE TITLE
[Feature]: Integrate Triton page/flash attention to vllm

### ISSUE THREAD

**Issue by chizhang118** [bd-iaas-us/vllm#32]
paged_attention_v2_kernel(FlagAttention)
paged_attention_v2_reduce_kernel(FlagAttention)

**Comment by JackChuang** [comment]
Replace vLLM CUDA kernels with Triton kernels:
https://bytedance.larkoffice.com/wiki/HHoiwbHbui1ZaKkYK3yclrXInvJ

**Comment by chizhang118** [comment]
page attention and flash attention for prefill triton support completed. Decode with KV cache needs to rewrite a new triton version method.

**Comment by chizhang118** [comment]
Needs thorough testing after https://github.com/bd-iaas-us/vllm/issues/43 completion. Now the code is ready for branch trion-npu-support.

**Comment by chizhang118** [comment]
The thorough testing will be done in https://github.com/bd-iaas-us/vllm/issues/36.
