### ISSUE TITLE
[Feature]:  AS - Enable truncation support in vLLM

### ISSUE THREAD

**Issue by JackChuang** [bd-iaas-us/vllm#39]
Current vLLM doesn't support truncation.

Future work: Truncation support is needed to test reusing the pre-rotary KV cache.

**Comment by JackChuang** [comment]
vLLM has introduced "truncate_prompt_tokens" but it does not support offline inference (located in vllm/entrypoints/llm.py) and only supports OpenAI entry points (found in vllm/entrypoints/openai/serving_engine.py).
  - Relevant but incomplete implementations and issues have been found in the Vllm community, and I've already asked the developers for more information:  https://github.com/vllm-project/vllm/pull/4598#issuecomment-2418962075

**Comment by XiaoningDing** [comment]
@thesues Could you help move all positional encoding issues to the repo of Infinistore? Thanks.
