### ISSUE TITLE
Sparse KV cache implementation

### ISSUE THREAD

**Issue by chizhang118** [bd-iaas-us/vllm#5]

**Comment by chizhang118** [comment]
Design doc - https://bytedance.larkoffice.com/wiki/CiW4wA3etijfWHkN8rWctNOQnxg

**Comment by guojunzzc** [comment]
> Design doc - https://bytedance.larkoffice.com/wiki/CiW4wA3etijfWHkN8rWctNOQnxg
> 
> https://bytedance.larkoffice.com/wiki/ShXJwPtyEiy9pKkVr0EcurS0nSg

could you please open this design doc, which we don't have access, thanks

**Comment by chizhang118** [comment]
> > Design doc - https://bytedance.larkoffice.com/wiki/CiW4wA3etijfWHkN8rWctNOQnxg
> > https://bytedance.larkoffice.com/wiki/ShXJwPtyEiy9pKkVr0EcurS0nSg
> 
> could you please open this design doc, which we don't have access, thanks

https://docs.google.com/document/d/13_cpb31P9VOmPGa_tZ70s7z1vXGP_UenXf1WVuIppCk/edit#heading=h.evhjclx158o3 Thanks for your interest. The updated doc is pasted in the google doc.
